// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9dwgqmuW5Xj5GloUhZiUdWBVZuaBPF_Q',
    appId: '1:753129101378:web:16a301105388a7497af5db',
    messagingSenderId: '753129101378',
    projectId: 'fir-classprojuct',
    authDomain: 'fir-classprojuct.firebaseapp.com',
    storageBucket: 'fir-classprojuct.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA8ZUd38CKk6qdAE-Zu_F2NnOIqan5bo4',
    appId: '1:753129101378:android:82f39f8b132739177af5db',
    messagingSenderId: '753129101378',
    projectId: 'fir-classprojuct',
    storageBucket: 'fir-classprojuct.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-YoAurmcZxUW3bnh1vVzB_CIWjwailbM',
    appId: '1:753129101378:ios:4907dc7b9038d52d7af5db',
    messagingSenderId: '753129101378',
    projectId: 'fir-classprojuct',
    storageBucket: 'fir-classprojuct.appspot.com',
    iosBundleId: 'com.example.firebaseClassProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-YoAurmcZxUW3bnh1vVzB_CIWjwailbM',
    appId: '1:753129101378:ios:4907dc7b9038d52d7af5db',
    messagingSenderId: '753129101378',
    projectId: 'fir-classprojuct',
    storageBucket: 'fir-classprojuct.appspot.com',
    iosBundleId: 'com.example.firebaseClassProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9dwgqmuW5Xj5GloUhZiUdWBVZuaBPF_Q',
    appId: '1:753129101378:web:de5a12dfee93688c7af5db',
    messagingSenderId: '753129101378',
    projectId: 'fir-classprojuct',
    authDomain: 'fir-classprojuct.firebaseapp.com',
    storageBucket: 'fir-classprojuct.appspot.com',
  );
}
