// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7j5eT3d9NtXbbkQnawz5KpJsvM55P2W8',
    appId: '1:755260312126:web:c701e30e0ef312fd761f6f',
    messagingSenderId: '755260312126',
    projectId: 'fir-chatapp-d8ec7',
    authDomain: 'fir-chatapp-d8ec7.firebaseapp.com',
    storageBucket: 'fir-chatapp-d8ec7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVArwjZ-zZqZYpHPSq7JGGH02j9T0x11Q',
    appId: '1:755260312126:android:bbbd2a6737f84a76761f6f',
    messagingSenderId: '755260312126',
    projectId: 'fir-chatapp-d8ec7',
    storageBucket: 'fir-chatapp-d8ec7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNCXbYEPIsqF_c94Nqw4wzwXewHfgFXgE',
    appId: '1:755260312126:ios:43b6a2ab043e0b71761f6f',
    messagingSenderId: '755260312126',
    projectId: 'fir-chatapp-d8ec7',
    storageBucket: 'fir-chatapp-d8ec7.appspot.com',
    iosBundleId: 'com.example.firebaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNCXbYEPIsqF_c94Nqw4wzwXewHfgFXgE',
    appId: '1:755260312126:ios:43b6a2ab043e0b71761f6f',
    messagingSenderId: '755260312126',
    projectId: 'fir-chatapp-d8ec7',
    storageBucket: 'fir-chatapp-d8ec7.appspot.com',
    iosBundleId: 'com.example.firebaseChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7j5eT3d9NtXbbkQnawz5KpJsvM55P2W8',
    appId: '1:755260312126:web:645d8a163fff3b1a761f6f',
    messagingSenderId: '755260312126',
    projectId: 'fir-chatapp-d8ec7',
    authDomain: 'fir-chatapp-d8ec7.firebaseapp.com',
    storageBucket: 'fir-chatapp-d8ec7.appspot.com',
  );
}
