// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcBjhxPEMOiPM2JfwDdQMsNIgD0bib0DA',
    appId: '1:323599180609:web:529d708a6094393de0f7c0',
    messagingSenderId: '323599180609',
    projectId: 'digitalsocity-d055f',
    authDomain: 'digitalsocity-d055f.firebaseapp.com',
    storageBucket: 'digitalsocity-d055f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl3a_8m8m9b8vMiRUG9bfSekQFhesMy9s',
    appId: '1:323599180609:android:97baa1d783c51bb2e0f7c0',
    messagingSenderId: '323599180609',
    projectId: 'digitalsocity-d055f',
    storageBucket: 'digitalsocity-d055f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-X6jUwHKsxoG2a_QmdMdQe_HyQ7xg65Y',
    appId: '1:323599180609:ios:b483ab25b84be1e6e0f7c0',
    messagingSenderId: '323599180609',
    projectId: 'digitalsocity-d055f',
    storageBucket: 'digitalsocity-d055f.appspot.com',
    iosBundleId: 'com.example.digitalSocity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-X6jUwHKsxoG2a_QmdMdQe_HyQ7xg65Y',
    appId: '1:323599180609:ios:b483ab25b84be1e6e0f7c0',
    messagingSenderId: '323599180609',
    projectId: 'digitalsocity-d055f',
    storageBucket: 'digitalsocity-d055f.appspot.com',
    iosBundleId: 'com.example.digitalSocity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcBjhxPEMOiPM2JfwDdQMsNIgD0bib0DA',
    appId: '1:323599180609:web:ce106bdb2d88ff66e0f7c0',
    messagingSenderId: '323599180609',
    projectId: 'digitalsocity-d055f',
    authDomain: 'digitalsocity-d055f.firebaseapp.com',
    storageBucket: 'digitalsocity-d055f.appspot.com',
  );
}
