// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYJo6pooFN4KYgN7hZOdvO_TSP-Tr5flY',
    appId: '1:354967120639:web:347b028cbddea9102efaca',
    messagingSenderId: '354967120639',
    projectId: 'fir-blood-bank-f821e',
    authDomain: 'fir-blood-bank-f821e.firebaseapp.com',
    storageBucket: 'fir-blood-bank-f821e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCj5qhnSFqefUvVws5ODgxQ1BVKdIcoKo',
    appId: '1:354967120639:android:5271b4897fa9636e2efaca',
    messagingSenderId: '354967120639',
    projectId: 'fir-blood-bank-f821e',
    storageBucket: 'fir-blood-bank-f821e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABw8f4RABhOJI43YaXQbfvJyIr5RXRy1Y',
    appId: '1:354967120639:ios:694bd9dbbe483db92efaca',
    messagingSenderId: '354967120639',
    projectId: 'fir-blood-bank-f821e',
    storageBucket: 'fir-blood-bank-f821e.appspot.com',
    iosBundleId: 'com.example.bloodBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABw8f4RABhOJI43YaXQbfvJyIr5RXRy1Y',
    appId: '1:354967120639:ios:694bd9dbbe483db92efaca',
    messagingSenderId: '354967120639',
    projectId: 'fir-blood-bank-f821e',
    storageBucket: 'fir-blood-bank-f821e.appspot.com',
    iosBundleId: 'com.example.bloodBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYJo6pooFN4KYgN7hZOdvO_TSP-Tr5flY',
    appId: '1:354967120639:web:84e9f346d3fd12c22efaca',
    messagingSenderId: '354967120639',
    projectId: 'fir-blood-bank-f821e',
    authDomain: 'fir-blood-bank-f821e.firebaseapp.com',
    storageBucket: 'fir-blood-bank-f821e.appspot.com',
  );
}
