// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8eAfzjhuvZDH8dLMPdrXKuuRU99-9ASM',
    appId: '1:903717385339:web:a73736f79224ee0f2d5ede',
    messagingSenderId: '903717385339',
    projectId: 'todo-applications-5bda4',
    authDomain: 'todo-applications-5bda4.firebaseapp.com',
    storageBucket: 'todo-applications-5bda4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAss6yjuLWd_PQTbT563P0O1bZiNn04eHU',
    appId: '1:903717385339:android:123f6da7db3a3ec12d5ede',
    messagingSenderId: '903717385339',
    projectId: 'todo-applications-5bda4',
    storageBucket: 'todo-applications-5bda4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Bvz-CV9a2MC7yIxVgX1c4mp2v-RiheM',
    appId: '1:903717385339:ios:c1114077a2dff5142d5ede',
    messagingSenderId: '903717385339',
    projectId: 'todo-applications-5bda4',
    storageBucket: 'todo-applications-5bda4.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Bvz-CV9a2MC7yIxVgX1c4mp2v-RiheM',
    appId: '1:903717385339:ios:c1114077a2dff5142d5ede',
    messagingSenderId: '903717385339',
    projectId: 'todo-applications-5bda4',
    storageBucket: 'todo-applications-5bda4.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8eAfzjhuvZDH8dLMPdrXKuuRU99-9ASM',
    appId: '1:903717385339:web:e7fa06b0df2e391a2d5ede',
    messagingSenderId: '903717385339',
    projectId: 'todo-applications-5bda4',
    authDomain: 'todo-applications-5bda4.firebaseapp.com',
    storageBucket: 'todo-applications-5bda4.appspot.com',
  );
}
